/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.SportGroup.sport.logic.ejb;

import co.edu.uniandes.csw.SportGroup.country.logic.entity.CountryEntity;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.SportGroup.sport.logic.api.ISportLogic;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportPageDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.converter.SportConverter;
import co.edu.uniandes.csw.SportGroup.sport.logic.entity.SportEntity;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@Default
@Stateless
@LocalBean
public class SportLogic implements ISportLogic {

    @PersistenceContext(unitName = "SportClassPU")
    protected EntityManager entityManager;

    public SportDTO createSport(SportDTO sport) {
        SportEntity entity = SportConverter.persistenceDTO2Entity(sport);
        CountryEntity country = this.getSelectedCountry(sport);
        if (country != null) {
            entity.setCountry(country);
        }
        entityManager.persist(entity);
        return SportConverter.entity2PersistenceDTO(entity);
    }

    public List<SportDTO> getSports() {
        Query q = entityManager.createQuery("select u from SportEntity u");
        return SportConverter.entity2PersistenceDTOList(q.getResultList());
    }

    public SportPageDTO getSports(Integer page, Integer maxRecords) {
        Query count = entityManager.createQuery("select count(u) from SportEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
        Query q = entityManager.createQuery("select u from SportEntity u");
        if (page != null && maxRecords != null) {
            q.setFirstResult((page - 1) * maxRecords);
            q.setMaxResults(maxRecords);
        }
        SportPageDTO response = new SportPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(SportConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
    }

    public SportDTO getSport(Long id) {
        return SportConverter.entity2PersistenceDTO(entityManager.find(SportEntity.class, id));
    }

    public void deleteSport(Long id) {
        SportEntity entity = entityManager.find(SportEntity.class, id);
        entityManager.remove(entity);
    }

    public void updateSport(SportDTO sport) {
        SportEntity entity = entityManager.merge(SportConverter.persistenceDTO2Entity(sport));
        CountryEntity country = this.getSelectedCountry(sport);
        if (country != null) {
            entity.setCountry(country);
        }
        SportConverter.entity2PersistenceDTO(entity);
    }
    private CountryEntity getSelectedCountry(SportDTO sport){
        if (sport != null && sport.getCountry() != null && sport.getCountry() != null) {
            return entityManager.find(CountryEntity.class, sport.getCountry());
        }else{
            return null;
        }
    }
}
