/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.SportGroup.sport.logic.ejb;

import javax.ejb.EJB;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.SportGroup.sport.logic.api.ISportLogic;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportPageDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.converter.SportConverter;
import co.edu.uniandes.csw.SportGroup.sport.logic.entity.SportEntity;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@Default
@Stateless
@LocalBean
public class ClientLogic implements IClientLogic {

    @PersistenceContext(unitName = "ClientClassClassPU")
    protected EntityManager entityManager;

    public ClientDTO createProvider(ClientDTO provider) {
        ClientEntity entity = ClientConverter.persistenceDTO2Entity(client);
        entityManager.persist(entity);
        return ClientConverter.entity2PersistenceDTO(entity);
    }

    public List<ClientDTO> getClients() {
        Query q = entityManager.createQuery("select u from ClientEntity u");
        return ClientConverter.entity2PersistenceDTOList(q.getResultList());
    }

    public ClientPageDTO getClients(Integer page, Integer maxRecords) {
        Query count = entityManager.createQuery("select count(u) from ClientEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
        Query q = entityManager.createQuery("select u from ClientEntity u");
        if (page != null && maxRecords != null) {
            q.setFirstResult((page - 1) * maxRecords);
            q.setMaxResults(maxRecords);
        }
        ClientPageDTO response = new ClientPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(ClientConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
    }

    public ClientDTO getClient(Long id) {
        return ClientConverter.entity2PersistenceDTO(entityManager.find(ClientEntity.class, id));
    }

    public void deleteClient(Long id) {
        ClientEntity entity = entityManager.find(ClientEntity.class, id);
        entityManager.remove(entity);
    }

    public void updateClient(ClientDTO client) {
        ClientEntity entity = entityManager.merge(ClientConverter.persistenceDTO2Entity(client));
        ClientConverter.entity2PersistenceDTO(entity);
    }
}
