/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.SportGroup.sport.logic.entity;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class ClientEntity {

    @Id
    @GeneratedValue(generator = "Client")
    private Long userId;
	
	private Integer userType;
	
	private String name;
	
        private String lastName;
        
	private String email;
	
	private String birthday;
	
	private Integer creditCard;
	
	
	
	public Long getUserId(){
		return userId;
	}
	
	public Integer getUserType(){
		return userType;
	}
	
	public String getName(){
		return name;
	}
	
        public String getLastName()
        {
            return lastName;
        }
        
	public String getEmail(){
		return email;
	}
	
	public String getBirthday(){
		return birthday;
	}
	
	public int getCerditcard(){
		return creditCard;
	}
    

	public void setUserId(Long userId){
		this.userId=userId;
	}
	
	public void setUserType(Integer userType){
		this.userType=userType;
	}
	
	public void setName(String name){
		this.name=name;
	}
	
        public void setLastName(String nLastName)
        {
            this.lastName = nLastName;
        }
        
	public void setEmail(String email){
		this.email=email;
	}
	
	public void setBirthday(String nBirthday){
		this.birthday=nBirthday;
	}
	
	public void setCreditCard(Integer nCreditCard){
		this.creditCard=nCreditCard;
	}
    
}
