/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.SportGroup.sport.logic.ejb;

import javax.ejb.EJB;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.SportGroup.sport.logic.api.ISportLogic;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.dto.SportPageDTO;
import co.edu.uniandes.csw.SportGroup.sport.logic.converter.SportConverter;
import co.edu.uniandes.csw.SportGroup.sport.logic.entity.SportEntity;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@Default
@Stateless
@LocalBean
public class ProviderLogic implements IProviderLogic {

    @PersistenceContext(unitName = "ProviderClassPU")
    protected EntityManager entityManager;

    public ProviderDTO createProvider(ProviderDTO provider) {
        ProviderEntity entity = ProviderConverter.persistenceDTO2Entity(provider);
        entityManager.persist(entity);
        return ProviderConverter.entity2PersistenceDTO(entity);
    }

    public List<ProviderDTO> getProviders() {
        Query q = entityManager.createQuery("select u from ProviderEntity u");
        return ProviderConverter.entity2PersistenceDTOList(q.getResultList());
    }

    public ProviderPageDTO getProviders(Integer page, Integer maxRecords) {
        Query count = entityManager.createQuery("select count(u) from ProviderEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
        Query q = entityManager.createQuery("select u from ProviderEntity u");
        if (page != null && maxRecords != null) {
            q.setFirstResult((page - 1) * maxRecords);
            q.setMaxResults(maxRecords);
        }
        ProviderPageDTO response = new ProviderPageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(ProviderConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
    }

    public ProviderDTO getProvider(Long id) {
        return ProviderConverter.entity2PersistenceDTO(entityManager.find(ProviderEntity.class, id));
    }

    public void deleteProvider(Long id) {
        ProviderEntity entity = entityManager.find(ProviderEntity.class, id);
        entityManager.remove(entity);
    }

    public void updateProvider(ProviderDTO provider) {
        ProviderEntity entity = entityManager.merge(ProviderConverter.persistenceDTO2Entity(provider));
        ProviderConverter.entity2PersistenceDTO(entity);
    }
}
